require_relative "version"
require_relative "generators/mongoid_model_maker/j_builder_generator"
require_relative "generators/mongoid_model_maker/factory_generator"
require_relative "generators/mongoid_model_maker/relation/relation_generator"
require_relative "yaml_loader"
require_relative "generators/mongoid_model_maker/full_generator"

module MongoidModelMaker
end
