require_relative "version"
require_relative "generators/mongoid_model_maker/scaffold_generator"
require_relative "generators/mongoid_model_maker/jbuilder_generator"
require_relative "generators/mongoid_model_maker/factories_generator"
require_relative "generators/mongoid_model_maker/relation/relation_generator"
require_relative "yaml_loader"
require_relative "generators/mongoid_model_maker/full_generator"

module MongoidModelMaker
end
